Controllers films users
cayoskoro/java-filmorate pull request #3
Opened 2023-09-30 15:19 UTC by cayoskoro

- Созданы модели User, Film с определенными правилами валидации;
- Создана кастомная аннотация-валидация для свойства releaseDate модели Film;
- Созданы контроллеры UserController, FilmController;
- Каждый контроллер имеет действия create, update, findAll;
- Создано исключение ValidationException для базовой валидации;
- Для проверки базовой валидации написаны тесты на методы контроллеров, где есть базовая валидация.

2023-10-01 14:11 UTC, Fleaman777 requested changes

2023-10-01 14:11 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
правильный вынос подобной логики в отдельный метод - использование принципа разделения ответсвенности

2023-10-01 14:11 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String description;
поля должны быть private

2023-10-01 14:11 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @PastOrPresent
хорошее использование валидационных аннотаций, помогают сократить "бойлер плейт" код, что повышает читаемость

2023-10-01 14:11 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    Film updatedFilm;
в тестах так же можно придерживаться принципа инкапсуляции

2023-10-01 14:11 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                "о Куглов, который за время «своего отсутствия», стал кандидатом Коломбани.")
подобные длинные строки можно вынести в константу, что бы не занимали место в самом тесте, что улучшило бы восприятие

2023-10-01 14:11 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void testUpdateWhenFilmWithDescriptionSizeMore200() {
хорошее название тест методов, из которого понятно, что именно делает тест

2023-10-01 20:43 UTC, cayoskoro commented
Поправил модификаторы доступа на private в моделях и тестах;
Вынес проверку на существование/выброс исключения реквест-объекта в отдельный метод в контроллерах;
Вынес тестовый пример description к константное поле.

2023-10-02 19:49 UTC, Fleaman777 approved these changes

2023-10-02 19:49 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
отлично, то, что нужно

2023-10-08 19:05 UTC, merged