Add friends likes
cayoskoro/java-filmorate pull request #4
Opened 2023-10-15 12:24 UTC by cayoskoro

- Созданы сервисные слои UserService, FilmService;
- Созданы хранилища FilmStorage, UserStorage;
- Создан ErrorHandler;
- Обновлены контроллеры с использованием новой логики сервисных слоев.

2023-10-16 18:06 UTC, Fleaman777 requested changes

2023-10-16 18:06 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +    }
в случаи, когда выбрасываются исключения, хорошо было бы добавить лог, что бы в случае ошибки, лучше понимать что пошло не так

2023-10-16 18:06 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    }
можно немного упростить 

@Override
public Film findById(Integer id) {
    Film film = films.get(id);
    if (film == null) {
        throw new NotFoundException("Film Not Found");
    }
    return film;
}

2023-10-16 18:06 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (Objects.isNull(films.get(film.getId()))) {
это конечно быть чистая вкусовщина, 
но я бы для проверки на null использовал бы == null

выглядит покороче, а смысл не меняется

2023-10-16 18:06 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new NotFoundException("Film Not Found");
"Film Not Found" не User ?

2023-10-18 15:47 UTC, cayoskoro commented
- Добавил использование @RequiredArgsConstructor;
- Добавил логирование исключений;
- Отрефакторил логику поиска ресурса;
- Заменил Objects.isNull на == null;
- Исправил текст исключения для метода update класса InMemoryUserStorage.

2023-10-19 07:59 UTC, Fleaman777 approved these changes

2023-10-20 20:08 UTC, merged